# Generated by Django 3.0.5 on 2020-04-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_col_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='col_test',
        ),
    ]
