# Generated by Django 3.0.5 on 2020-04-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_col_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='col_test',
            field=models.CharField(default='', max_length=100),
        ),
    ]
